name: "Backend/PHP smoke test: Minimal checks for Symfony framework"

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: PHP version
        run: php -v

      - name: Composer version
        run: composer --version

      - name: Install PHP dependencies
        run: APP_ENV=prod composer install --prefer-dist --no-progress --no-suggest --no-dev

      - name: Check symfony version
        run: APP_ENV=prod bin/console -V