name: "Frontend/JavaScript smoke test: Minimal checks for Symfony Encore and assets building"

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Node.js version
        run: node -v

      - name: Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn

      - name: Build assets
        run: yarn run encore production